03-11-2022 15:20:54 | INFO | Snowflake Connector for Python Version: 2.8.0, Python Version: 3.10.0, Platform: Windows-10-10.0.19044-SP0
03-11-2022 15:20:54 | INFO | This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
03-11-2022 15:20:54 | INFO | Setting use_openssl_only mode to False
03-11-2022 15:20:54 | WARNING | Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x000001D245BDC640>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /session/v1/login-request?request_id=50b8f134-30c1-4703-af44-c40431ae6e07&databaseName=%3CYOUR+SNOWFLAKE+DATABASE%3E&schemaName=%3CYOUR+SNOWFLAKE+SCHEMA%3E&warehouse=%3CYOUR+SNOWFLAKE+DW+NAME%3E&request_guid=7826350b-9e82-4798-a52f-11a1e5bb9431
03-11-2022 15:20:57 | WARNING | Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x000001D245BDCF40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /session/v1/login-request?request_id=4dbb1b28-36fb-451c-b566-f98061650aef&databaseName=%3CYOUR+SNOWFLAKE+DATABASE%3E&schemaName=%3CYOUR+SNOWFLAKE+SCHEMA%3E&warehouse=%3CYOUR+SNOWFLAKE+DW+NAME%3E&request_guid=bbbabe12-8961-4bd1-9405-dc36fb98de90
03-11-2022 15:20:58 | INFO | closed
