04-11-2022 11:40:15 | INFO | Snowflake Connector for Python Version: 2.8.0, Python Version: 3.10.0, Platform: Windows-10-10.0.19044-SP0
04-11-2022 11:40:15 | INFO | This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
04-11-2022 11:40:15 | INFO | Setting use_openssl_only mode to False
04-11-2022 11:40:15 | WARNING | Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x000001DC9366C670>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /session/v1/login-request?request_id=36bee0b2-2df1-446f-87eb-ccef206e8473&databaseName=%3CYOUR+SNOWFLAKE+DATABASE%3E&schemaName=%3CYOUR+SNOWFLAKE+SCHEMA%3E&warehouse=%3CYOUR+SNOWFLAKE+DW+NAME%3E&request_guid=11ff2f81-3f5e-44e9-9a92-f01e791269c1
04-11-2022 11:40:16 | WARNING | Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x000001DC9366CF70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /session/v1/login-request?request_id=81e7c4a6-9fb2-41e4-bc6c-65be89f2db74&databaseName=%3CYOUR+SNOWFLAKE+DATABASE%3E&schemaName=%3CYOUR+SNOWFLAKE+SCHEMA%3E&warehouse=%3CYOUR+SNOWFLAKE+DW+NAME%3E&request_guid=b3d93748-765a-4e2a-a11a-c66748a95648
04-11-2022 11:40:16 | INFO | closed
