16-12-2022 13:59:18 | INFO | Snowflake Connector for Python Version: 2.9.0, Python Version: 3.10.0, Platform: Windows-10-10.0.19044-SP0
16-12-2022 13:59:18 | INFO | This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
16-12-2022 13:59:18 | INFO | Setting use_openssl_only mode to False
16-12-2022 13:59:18 | WARNING | Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x000001CEE9454700>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /session/v1/login-request?request_id=35660222-4496-4f73-a190-62a3c36a3c60&databaseName=%3CYOUR+SNOWFLAKE+DATABASE%3E&schemaName=%3CYOUR+SNOWFLAKE+SCHEMA%3E&warehouse=%3CYOUR+SNOWFLAKE+DW+NAME%3E&request_guid=52ef7ecb-31a6-421a-b0f1-90a4000e312d
16-12-2022 13:59:21 | WARNING | Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x000001CEE9455060>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /session/v1/login-request?request_id=8d0d73c9-72aa-4db3-b1ca-e247e1e03539&databaseName=%3CYOUR+SNOWFLAKE+DATABASE%3E&schemaName=%3CYOUR+SNOWFLAKE+SCHEMA%3E&warehouse=%3CYOUR+SNOWFLAKE+DW+NAME%3E&request_guid=eaf4affc-57e8-469a-adcd-1f47f44afd4e
16-12-2022 13:59:21 | INFO | closed
