16-12-2022 12:23:39 | INFO | Snowflake Connector for Python Version: 2.8.3, Python Version: 3.9.6, Platform: Windows-10-10.0.19044-SP0
16-12-2022 12:23:39 | INFO | This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
16-12-2022 12:23:39 | INFO | Setting use_openssl_only mode to False
16-12-2022 12:23:39 | WARNING | Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x000002250AEA6220>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /session/v1/login-request?request_id=44675e33-34ec-420f-9022-98ccabec865c&databaseName=%3CYOUR+SNOWFLAKE+DATABASE%3E&schemaName=%3CYOUR+SNOWFLAKE+SCHEMA%3E&warehouse=%3CYOUR+SNOWFLAKE+DW+NAME%3E&request_guid=df65f4ba-9159-4cd8-8c47-0af36bbec29b
16-12-2022 12:23:41 | WARNING | Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x000002250AEE4820>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /session/v1/login-request?request_id=066114dc-4092-4068-a976-7fe9b2d98295&databaseName=%3CYOUR+SNOWFLAKE+DATABASE%3E&schemaName=%3CYOUR+SNOWFLAKE+SCHEMA%3E&warehouse=%3CYOUR+SNOWFLAKE+DW+NAME%3E&request_guid=102dafc4-6801-4ab3-8e8c-22f6ff78f984
